create table courses(
    stud_id numeric(10) Generated by default as identity start with 001 increment by 1,
    course_name varchar2(50),
    course_id numeric(10),
    constraint course_id_pk primary key(course_id)
);

insert into courses(course_id, course_name)
with ABC as(
    select 101, 'SQL' from dual union ALL
    select 102, 'JAVA' from dual union all
    select 103, 'PYTHON' from dual union all
    select 104, 'CPP' from dual union all
    select 105, 'TESTING' from dual 
) Select * from ABC;
select * from courses;

desc courses;

create table employees(
    employee_id numeric(6) Generated always as identity start with 001 increment by 1 ,
    first_name varchar2(45),
    last_name varchar2(45),
    salary numeric(10),
    department_id numeric(10),
    CONSTRAINT employee_id_pk primary key(employee_id)
);

insert into employees(first_name, last_name,salary, department_id)
with ABC as(
    select 'Shivam', 'Pathak', 23000, 123 from dual union all
    select 'Harshit', 'Dubey', 25000, 125 from dual union all
    select 'Nishi', 'Mishra', 35000, 127  from dual
) select * from ABC;
select * from employees;

update employees set first_name=upper(first_name);
select * from employees;


select employee_id,last_name,salary, salary+(salary*0.16) as salary1 from hr.employees;

SELECT 
    employee_id,
    salary AS old_salary,
    salary * 1.16 AS new_salary,
    (salary * 1.16 - salary) AS salary_increase
FROM employees;
